name = "ex_gleam_github_oauth"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
wisp = ">= 0.14.0 and < 1.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
carpenter = ">= 0.3.1 and < 1.0.0"
radish = ">= 0.15.0 and < 1.0.0"
gluid = ">= 1.0.0 and < 2.0.0"
dot_env = ">= 0.5.1 and < 1.0.0"
glenvy = ">= 1.0.0 and < 2.0.0"
mist = ">= 1.2.0 and < 2.0.0"
gleam_httpc = ">= 2.2.0 and < 3.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
flash = ">= 1.0.0 and < 2.0.0"
glow_auth = ">= 0.4.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
