[package]
name = "rust-sled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
sled = "0.34.7"
uuid = { version = "1.4.1", features = ["v4"] }
