// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");

function fizzbuzz(n) {
  if (n % 15 === 0) {
    return "FizzBuzz";
  } else if (n % 3 === 0) {
    return "Fizz";
  } else if (n % 5 === 0) {
    return "Buzz";
  } else {
    return String(n);
  }
}

console.log(Belt_Array.joinWith(Belt_Array.map(Belt_Array.range(0, 30), (function (n) {
                return fizzbuzz(n);
              })), "\n", (function (s) {
            return s;
          })));

exports.fizzbuzz = fizzbuzz;
/*  Not a pure module */
