workspace = { members = ["extism-plugin"] }
[package]
name = "rust-extism"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extism = "1.0.3"
