services:
  postgres:
    networks:
      - container_network

    container_name: ex_gleam_pgo_postgres
    image: postgres:latest
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - type: bind
        source: "./postgre"
        target: "/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  gleam:
    networks:
      - container_network

    container_name: ex_gleam_pgo_gleam
    build:
      context: .
      dockerfile: ./gleam.dockerfile 
    ports: 
      - "8000:8000"
    environment:
      PG_HOST: "ex_gleam_pgo_postgres"

networks:
  container_network:
    external: true  
